#Splash screen properties
#Tue Jun 08 16:41:14 MSK 2021
background=0xffffff
memoryGood=0x85ff9b
font=0x0
barBackground=0x828282
barBorder=0xffffff
memoryLow=0x9e0505
rotate=false
memoryWarn=0xffd64f
showMemory=true
enabled=true
bar=0x85ff9b
resourcePackPath=resources
logoOffset=500
forgeTexture=fml\:textures/gui/forge.png
fontTexture=textures/font/ascii.png
