# The default configuration by dimension when no world name matches
Dimensions {
    "minecraft:nether"=nether
    "minecraft:the_end"="the_end"
}
# The default configuration used when no dimension matches
Global=overworld
# The configurations associated to specific world names
Worlds {}
